# Generated by Django 5.2.14 on 2026-05-13 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vert_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='vert_core.pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='vert_core.owner'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='vert_core.pet'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='vert_core.pet'),
        ),
    ]
