# Generated by Django 5.2.14 on 2026-06-16 21:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vert_core', '0003_remove_pet_owner_remove_vaccine_pet_remove_visit_pet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='user_name',
        ),
    ]
