# Generated by Django 5.2.14 on 2026-06-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vert_core', '0004_rename_recipe_user_rename_user_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='recipe_description',
            new_name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='recipe_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='recipe_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='recipe_view_count',
        ),
        migrations.AddField(
            model_name='user',
            name='pet_image',
            field=models.ImageField(default='pets/default.png', upload_to='pets'),
        ),
    ]
